### ISSUE TITLE
Binder env not working for local COG

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver-demo#1]
The binder env works well when rending a remote COG. However, it does not seem to work for a local COG (a file in the repo). The tile layer won't show up.  

```
!wget https://github.com/giswqs/data/raw/main/raster/srtm90.tif
```

```python
from localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

# First, create a tile server from local raster file
tile_client = TileClient('srtm90.tif')

# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(tile_client)

# Create ipyleaflet map, add tile layer, and display
m = Map(center=tile_client.center())
m.add_layer(t)
m
```

**Comment by banesullivan** [comment]
This is known/expected because of https://github.com/banesullivan/localtileserver/issues/29

I do not know of a way to expose a server from the binder env that is accessible in the user's browser

**Comment by banesullivan** [comment]
`TileClient` will not work in this sort of environment, only `RemoteTileClient` which is connecting to a production server I have running (not very performant)

**Comment by giswqs** [comment]
I was exploring the following repo this morning. It can run a streamlit web app on Binder. Not sure if it would be useful in your case.  

https://github.com/chekos/testing-streamlit-mybinder
https://mybinder.org/v2/gh/chekos/testing-streamlit-mybinder/master?urlpath=proxy/8501/

**Comment by banesullivan** [comment]
Ah, that demo is just what I needed to see! I will see if I can do something similar with localtileserver

**Comment by banesullivan** [comment]
This is now working using `jupyter-server-proxy`. Please note the line at the top of [`example.ipynb`](https://github.com/banesullivan/localtileserver-demo/blob/main/example.ipynb) that enables this to work:

```py
# Set host forwarding for MyBinder
import os
# Make sure `notebooks.gesis.org/binder/jupyter/user/` matches your URL address
os.environ['LOCALTILESERVER_CLIENT_HOST'] = f"notebooks.gesis.org/binder/jupyter/user/{os.environ['JUPYTERHUB_USER']}"
```

That HOST URL might change on different mybinder or jupyterhub deployments

**Comment by giswqs** [comment]
I just tested it on binder with the latest localtilesever. It does not seem to work. 

https://gishub.org/leafmap-binder

![image](https://user-images.githubusercontent.com/5016453/152669212-663437fe-e624-4c1b-95b2-1b9eac5b3c51.png)

**Comment by banesullivan** [comment]
Make sure to use the --pre flag for pip as I only released a dev version for this 0.4.1.dev0

I want to double check things before doing an actual release

**Comment by banesullivan** [comment]
Also, you'll need to install https://jupyter-server-proxy.readthedocs.io/en/latest/ and make sure its extensions are enabled

**Comment by banesullivan** [comment]
Ignore the --pre flag comment. Just noticed you're installing from git

**Comment by giswqs** [comment]
This is what I tried with my leafmap binder. Still not working. Not sure what I did wrong. 

https://gishub.org/leafmap-binder

```
!pip install git+https://github.com/banesullivan/localtileserver.git
!pip install jupyter-server-proxy
!jupyter serverextension enable --sys-prefix jupyter_server_proxy
```
![image](https://user-images.githubusercontent.com/5016453/152669434-6e352afb-8abe-44ad-9478-acd12aa444f0.png)

**Comment by giswqs** [comment]
Your gesis binder works fine. So the issue is probably related to how the binder env is set up. Your uses docker, mine uses [environment.yml](https://github.com/giswqs/leafmap/blob/master/environment.yml)

![image](https://user-images.githubusercontent.com/5016453/152669601-8d10d383-c117-4313-8b71-855ac3dcac69.png)

**Comment by banesullivan** [comment]
I think you'll have to relaunch Jupyter after enabling the server extension 

Also make sure that code block at the top setting `LOCALTILESERVER_CLIENT_HOST` is uncommented and that variable is set

**Comment by giswqs** [comment]
Yes, i did restart the kernel several times. Also uncommented that line. Still not working. Will look into it tomorrow. Thanks

**Comment by banesullivan** [comment]
After uncommenting that line, make sure that value matches the URL in your browser

**Comment by giswqs** [comment]
Is this correct?

```python
if os.environ.get('JUPYTERHUB_USER'):  
    os.environ['LOCALTILESERVER_CLIENT_HOST'] = f"hub.gke2.mybinder.org/user/{os.environ['JUPYTERHUB_USER']}"
else:
    os.environ['LOCALTILESERVER_CLIENT_PORT'] = '8888'
    os.environ['LOCALTILESERVER_CLIENT_HOST'] = "127.0.0.0"
    os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = 'proxy/{port}'
```

**Comment by banesullivan** [comment]
You need to set `os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = 'proxy/{port}'` in both cases

note that MyBinder's host can change anytime you launch, so `hub.gke2.mybinder.org/user/` will not always be correct

**Comment by giswqs** [comment]
Is there a way to retrieve the host URL programmatically?

**Comment by banesullivan** [comment]
There's always a way! ....but I couldn't figure it out... 😞 

The host is not listed in `os.environ` but it could be somewhere...

I tried:

```py
from notebook import notebookapp
servers = list(notebookapp.list_running_servers())
print(servers)
```
`... 'hostname': '0.0.0.0' ...`

But there's another webserver on top that manages the traffic.

I bet we could make a super hacky way of getting this through a custom ipython widget where the widget accesses `window.location.href` in the browser and then sends that data back to Python. However, this would be quite hacky and would require the user to display the widget. 

This question might be something https://discourse.jupyter.org/c/binder/12 could help address

**Comment by banesullivan** [comment]
ACTUALLY! I just found a much, much simpler way to do this.

**Comment by banesullivan** [comment]
I will follow up in a PR in localtileserver

**Comment by banesullivan** [comment]
See https://github.com/banesullivan/localtileserver/pull/67

After that, the following should be sufficient:

```py
# Set host forwarding for MyBinder
import os
os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = f"{os.environ['JUPYTERHUB_SERVICE_PREFIX'].lstrip('/')}/proxy/{{port}}"
```

**Comment by giswqs** [comment]
Fantastic! I can confirm that v0.4.3 works like a charm with Binder. How to make it work with other remote environments not using JupyterHub (e.g., streamlit)? 

```python
# Set host forwarding for MyBinder
import os
os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = f"{os.environ['JUPYTERHUB_SERVICE_PREFIX'].lstrip('/')}/proxy/{{port}}"
```

**Comment by banesullivan** [comment]
> How to make it work with other remote environments not using JupyterHub (e.g., streamlit)?

Let's open a new issue in `localtileserver` to address this

It should be a simple configuration with the settings I added for JupyterHub

**Comment by wzp8023391** [comment]
how to display raster image in remote environments, especially for streamlit?

**Comment by giswqs** [comment]
@wzp8023391 Unfortunately, localtileserver does not support streamlit. It is a streamlit problem rather than localtileserver.
